module Paseto
  class Key
    @secret: bool

    public

    attr_reader version: String
    attr_reader purpose: String

    def self.keysize: -> Integer

    def header: -> String

    def secret?: -> bool

    private

    attr_reader key: String

    def initialize: (version: String, purpose: String, ikm: String) -> void
  end
end
