module Paseto
  class Key
    attr_reader version: String
    attr_reader purpose: String

    def header: -> String
    def pae_header: -> String

    private
    
    def initialize: (version: String, purpose: String) -> void
  end
end
