module Paseto
  class Key
    attr_reader version: String
    attr_reader purpose: String
    attr_reader public_key: String | nil

    def self.keysize: -> Integer

    def header: -> String

    private

    attr_reader secret_key: String

    def initialize: (version: String, purpose: String, secret_key: String, ?public_key: (String | nil)) -> void
  end
end
