module Paseto
  class SymmetricKey
    HEADER: "v4.local"

    attr_reader ikm: String
    attr_reader version: Paseto::Versions::BaseVersion

    def initialize: (ikm: String, version: Paseto::Versions::BaseVersion) -> void
    def valid_for?: (version: Paseto::Versions::BaseVersion, purpose: 'local') -> (false | true)
  end
end
