---

detectors:
  IrresponsibleModule:
    enabled: false
  UncommunicativeModuleName:
    enabled: false
  UncommunicativeMethodName:
    exclude:
      - "Paseto::Util"
  UncommunicativeVariableName:
    enabled: false
  UncommunicativeParameterName:
    enabled: false
  ControlParameter:
    exclude:
      - "Paseto::Key#valid_for?"
  TooManyStatements:
    enabled: false
  UtilityFunction:
    exclude:
      - "RbNaCl::Stream::Base#data_len"
  InstanceVariableAssumption:
    exclude:
      - "RbNaCl::Stream::XChaCha20Xor"
  NilCheck:
    exclude:
      - "RbNaCl::Stream::Base#data_len"
  FeatureEnvy:
    exclude:
      - "Paseto::V4::Local#decrypt"
  DuplicateMethodCall:
    exclude:
      - "Paseto::Util.constant_compare"
