---

detectors:
  IrresponsibleModule:
    enabled: false
  UncommunicativeModuleName:
    enabled: false
  UncommunicativeMethodName:
    exclude:
      - "Paseto#self.decode64"
      - "Paseto#self.encode64"
      - "Paseto#self.le64"
  UncommunicativeVariableName:
    enabled: false
  ControlParameter:
    exclude:
      - "Paseto::Key::Base#valid_for?"
  TooManyStatements:
    exclude:
      - "RbNaCl::Stream::Base#encrypt"
      - "Paseto::V4::Local#encrypt"
  UtilityFunction:
    exclude:
      - "RbNaCl::Stream::Base#data_len"
  InstanceVariableAssumption:
    exclude:
      - "RbNaCl::Stream::XChaCha20Xor"
  NilCheck:
    exclude:
      - "RbNaCl::Stream::Base#data_len"
