---

detectors:
  IrresponsibleModule:
    enabled: false
  UncommunicativeModuleName:
    enabled: false
  MissingSafeMethod:
    enabled: false
  UnusedParameters:
    enabled: false
  UncommunicativeVariableName:
    enabled: false
  UncommunicativeParameterName:
    enabled: false
  TooManyStatements:
    enabled: false
  UncommunicativeMethodName:
    enabled: false
  
  LongParameterList:
    max_params: 4
  UtilityFunction:
    public_methods_only: true

  ControlParameter:
    exclude:
      - "Paseto::Key#valid_for?"
  FeatureEnvy:
    exclude:
      - "Paseto::V4::Local#decrypt"
  DuplicateMethodCall:
    exclude:
      - "Paseto::Util.constant_compare"
  TooManyConstants:
    exclude:
      - 'Paseto::Verify::Verifiers'
  Attribute:
    exclude:
      - 'Paseto::Configuration'
  ManualDispatch:
    exclude:
      - 'Paseto::Validator::TokenIdentifier#verify'
  DataClump:
    exclude:
      - 'Paseto::Interface'

exclude_paths:
  - spec/generate_vectors.rb
  - spec/**/test_vectors_spec.rb
  - lib/paseto/configuration/decode_configuration.rb
