require:
  - rubocop-performance
  - rubocop-rspec
  - rubocop-sorbet

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  Exclude:
    - 'tmp/**/*'
    - 'vendor/**/*'
    - '.git/**/*'
    - 'spec/vectors/**/*'
    - 'bin/*'
    - 'gemfiles/**/*'

Layout/LineLength:
  Max: 140

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 15
  Exclude:
    - 'spec/generate_vectors.rb'

Layout/ClosingHeredocIndentation:
  Exclude:
    - 'spec/generate_vectors.rb'

Layout/HeredocIndentation:
  Exclude:
    - 'spec/generate_vectors.rb'

Metrics/AbcSize:
  Max: 20
  Exclude:
    - 'spec/generate_vectors.rb'

Metrics/ParameterLists:
  Exclude:
    - 'spec/generate_vectors.rb'

Style/MutableConstant:
  Exclude:
    - 'spec/generate_vectors.rb'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Style/AccessorGrouping:
  Enabled: false

Sorbet/ConstantsFromStrings:
  Exclude:
    - 'lib/paseto/sodium/stream/base.rb'

RSpec/MultipleMemoizedHelpers:
  Exclude:
    - 'spec/paseto/token_validator_spec.rb'
    - 'spec/paseto/verify_spec.rb'

Naming/VariableNumber:
  CheckSymbols: false

Naming/MethodParameterName:
  Exclude:
    - 'lib/paseto/asn1'

Lint/MissingSuper:
  Enabled: false
