require:
  - rubocop-performance
  - rubocop-rake
#  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable
  Exclude:
    - 'spec/paseto/**/test_vectors_spec.rb'

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 140

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 15
  Exclude:
    - 'spec/generate_vectors.rb'

Layout/ClosingHeredocIndentation:
  Exclude:
    - 'spec/generate_vectors.rb'

Layout/HeredocIndentation:
  Exclude:
    - 'spec/generate_vectors.rb'

Metrics/AbcSize:
  Exclude:
    - 'spec/generate_vectors.rb'

Metrics/ParameterLists:
  Exclude:
    - 'spec/generate_vectors.rb'

Style/MutableConstant:
  Exclude:
    - 'spec/generate_vectors.rb'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
