gem:
  # Add your `gem` command parameters here:
  #
  # exclude:
  # - gem_name
  # doc: true
  # workers: 5
  exclude:
  - appraisal
  - parallel_tests
  - parlour
  - parser
  - paseto
  - rbi
  - reek
  - rspec_junit_formatter
  - rubocop
  - rubocop-ast
  - rubocop-performance
  - rubocop-rspec
  - rubocop-sorbet
  - spoom
  - tapioca
  - unparser
dsl:
  # Add your `dsl` command parameters here:
  #
  # exclude:
  # - SomeGeneratorName
  # workers: 5
