gem:
  # Add your `gem` command parameters here:
  #
  # exclude:
  # - gem_name
  # doc: true
  # workers: 5
  exclude:
  - flay
  - flog
  - reek
  - rubocop
  - rubocop-ast
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec
dsl:
  # Add your `dsl` command parameters here:
  #
  # exclude:
  # - SomeGeneratorName
  # workers: 5
