gem:
  # Add your `gem` command parameters here:
  #
  # exclude:
  # - gem_name
  # doc: true
  # workers: 5
  exclude:
  - flay
  - flog
  - parlour
  - oj
  - reek
  - rubocop
  - rubocop-ast
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec
  - rubocop-sorbet
dsl:
  # Add your `dsl` command parameters here:
  #
  # exclude:
  # - SomeGeneratorName
  # workers: 5
