# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

shared_env: &shared_env
  TEST_QUEUE_WORKERS: 2
  CC_TEST_REPORTER_ID: 9643f9411ff1c1d359175e948cf67205d2c35883e9dc2a6d45ffde54829abfb2

commands:
  bundle-install:
    description: "bundle install"
    parameters:
      appraisal:
          type: string
          default: standalone
      version:
          type: string
          default: "3.1"
    steps:
      - restore_cache:
          keys:
            - gem-cache-v4-<< parameters.version >>-{{ arch }}-{{ checksum "gemfiles/<< parameters.appraisal >>.gemfile.lock" }}
            - gem-cache-v4-<< parameters.version >>-{{ arch }}
      - run:
          name: "Install gems and appraisals"
          command : |
            bundle install --path=vendor/bundle
            bundle exec appraisal install --path=vendor/bundle
      - save_cache:
          key: gem-cache-v4-<< parameters.version >>-{{ arch }}-{{ checksum "gemfiles/<< parameters.appraisal >>.gemfile.lock" }}
          paths:
            - vendor/bundle

jobs:
  specs:
    parameters:
      version:
        type: string
        default: "3.1"
      appraisal:
        type: string
        default: standalone
    docker:
      - image: cimg/ruby:<< parameters.version >>
    environment:
      <<: *shared_env
    steps:
      - checkout
      - attach_workspace:
          at: tmp
      - bundle-install:
          appraisal: << parameters.appraisal >>
          version: << parameters.version >>
      - run:
          name: Run specs
          command: |
            ./tmp/cc-test-reporter before-build
            bundle exec appraisal << parameters.appraisal >> rake spec
            ./tmp/cc-test-reporter format-coverage --output tmp/codeclimate.$CIRCLE_JOB.json
      - persist_to_workspace:
          root: tmp
          paths:
            - codeclimate.*.json

  circleci-setup:
    docker:
      - image: cimg/ruby:3.1
    steps:
      - run:
          name: Download Code Climate test-reporter
          command: |
            mkdir -p tmp
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./tmp/cc-test-reporter
            chmod +x ./tmp/cc-test-reporter
      - persist_to_workspace:
          root: tmp
          paths:
            - cc-test-reporter

  circleci-upload:
    docker:
      - image: cimg/ruby:3.1
    environment:
      <<: *shared_env
    steps:
      - attach_workspace:
          at: tmp
      - run:
          name: Upload coverage results to Code Climate
          command: |
            ./tmp/cc-test-reporter sum-coverage tmp/codeclimate.*.json --parts 4 --output tmp/codeclimate.total.json
            ./tmp/cc-test-reporter upload-coverage --input tmp/codeclimate.total.json

  rubocop:
    docker:
      - image: cimg/ruby:3.1
    steps:
      - checkout
      - bundle-install
      - run:
          name: "Rubocop"
          command: |
            bundle exec rubocop --parallel

  typecheck:
    docker:
      - image: cimg/ruby:3.1
    steps:
      - checkout
      - bundle-install
      - run:
          name: "Sorbet Typecheck"
          command: |
            bundle exec srb tc

workflows:
  build:
    jobs:
      - circleci-setup
      - typecheck:
          requires:
            - circleci-setup
      - rubocop:
          requires:
            - typecheck
      - specs:
          name: ruby-3.0-specs-standalone
          requires:
            - typecheck
          version: "3.0"
      - specs:
          name: ruby-3.0-specs-rbnacl
          appraisal: rbnacl
          requires:
            - typecheck
          version: "3.0"
      - specs:
          name: ruby-3.1-specs-standalone
          requires:
            - typecheck
      - specs:
          name: ruby-3.1-specs-rbnacl
          appraisal: rbnacl
          requires:
            - typecheck
      - circleci-upload:
          requires:
            - ruby-3.1-specs-standalone
            - ruby-3.1-specs-rbnacl
            - ruby-3.0-specs-standalone
            - ruby-3.0-specs-rbnacl
