# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

shared_env: &shared_env
  TEST_QUEUE_WORKERS: 2
  CC_TEST_REPORTER_ID: 9643f9411ff1c1d359175e948cf67205d2c35883e9dc2a6d45ffde54829abfb2

executors:
  ruby-other:
    parameters:
      version:
        type: string
        default: "3.1"
    docker:
      - image: cimg/ruby:<< parameters.version >>
    environment:
      <<: *shared_env
    resource_class: medium+
  ruby-specs:
    parameters:
      version:
        type: string
        default: "3.1"
    docker:
      - image: cimg/ruby:<< parameters.version >>
    environment:
      <<: *shared_env
    resource_class: large

commands:
  load-dependencies:
    description: "Load gems into workspace and configure bundler"
    parameters:
      appraisal:
        type: string
        default: standalone
    steps:
      - install-bundler:
          appraisal: << parameters.appraisal >>
      - attach_workspace:
          at: vendor
      - run:
          name: "Configure Bundler"
          command : |
            #!/usr/bin/env bash

            bundle config set deployment 'true'
            bundle config set path "./vendor/bundle"

  install-bundler:
    description: "Install the appropriate bundler version for an appraisal lockfile"
    parameters:
      appraisal:
        type: string
    steps:
      - run:
          name: "Install bundler"
          command : |
            #!/usr/bin/env bash

            TARGET_GEMFILE="./gemfiles/$PARAM_APPRAISAL.gemfile.lock"

            APP_BUNDLER_VERSION=$(tail -1 $TARGET_GEMFILE | tr -d " ")
            if [ -z "$APP_BUNDLER_VERSION" ]; then
              echo "Could not find bundler version from lockfile."
              exit 1
            else
              echo "Lock file detected bundler version $APP_BUNDLER_VERSION"
            fi

            if ! bundle version | grep -q $APP_BUNDLER_VERSION; then
              echo "Installing bundler $APP_BUNDLER_VERSION"
              gem install bundler:$APP_BUNDLER_VERSION
            else
              echo "bundler $APP_BUNDLER_VERSION is already installed."
            fi
          environment:
            PARAM_APPRAISAL: << parameters.appraisal >>

jobs:
  install-dependencies:
    description: "Install gems with bundler and appraisal"
    parameters:
      version:
        type: string
        default: "3.1"
    executor:
      name: ruby-other
      version: << parameters.version >>
    steps:
      - checkout
      - restore_cache:
          keys:
            - gem-cache-v4-<< parameters.version >>-{{ arch }}-{{ checksum "Gemfile" }}-{{ checksum "gemfiles/standalone.gemfile.lock" }}-{{ checksum "gemfiles/rbnacl.gemfile.lock" }}
            - gem-cache-v4-<< parameters.version >>-{{ arch }}-{{ checksum "Gemfile" }}
            - gem-cache-v4-<< parameters.version >>-{{ arch }}
      - install-bundler:
          appraisal: rbnacl
      - run:
          name: "Bundle/Appraisal Install"
          command : |
            #!/usr/bin/env bash

            bundle config set deployment 'true'
            bundle config set path "./vendor/bundle"

            bundle install
            bundle exec appraisal install
      - save_cache:
          key: gem-cache-v4-<< parameters.version >>-{{ arch }}-{{ checksum "Gemfile" }}-{{ checksum "gemfiles/standalone.gemfile.lock" }}-{{ checksum "gemfiles/rbnacl.gemfile.lock" }}
          paths:
            - ./vendor/bundle
      - persist_to_workspace:
          root: vendor
          paths:
            - bundle/
  specs:
    parameters:
      version:
        type: string
        default: "3.1"
      appraisal:
        type: string
        default: standalone
    executor:
      name: ruby-specs
      version: << parameters.version >>
    parallelism: 4
    steps:
      - checkout
      - attach_workspace:
          at: tmp
      - load-dependencies:
          appraisal: << parameters.appraisal >>
      - run:
          name: Run specs
          command: |
            #!/usr/bin/env bash

            if ! mkdir -p "/tmp/test-results/"; then
              printf '%s\n' "Failed to create output directory: /tmp/test-results/rspec"
              exit 1
            fi

            readonly o_ifs="$IFS"
            IFS=","
            read -ra specs \<<< "spec/**/*_spec.rb"
            circle_split=$(circleci tests glob "${specs[@]}" | circleci tests split --split-by=timings)
            while IFS= read -r line; do spec_files+=("$line"); done \<<< "$circle_split"

            IFS="$o_ifs"

            set -x
            bundle exec appraisal << parameters.appraisal >> rspec "${spec_files[@]}" --profile 10 --order random --format progress --format RspecJunitFormatter -o /tmp/test-results/rspec
            set +x
            ./tmp/cc-test-reporter format-coverage --output tmp/codeclimate.$CIRCLE_JOB-$CIRCLE_NODE_INDEX.json
      - store_test_results:
          path: /tmp/test-results/rspec
      - persist_to_workspace:
          root: tmp
          paths:
            - codeclimate.*.json

  codeclimate-setup:
    executor: ruby-other
    steps:
      - run:
          name: Download latest cc-test-reporter signature
          command: |
            #!/usr/bin/env bash

            if ! mkdir -p tmp; then
              printf '%s\n' "Failed to create tmp directory!"
              exit 1
            fi

            SUM=$(curl -s -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64.sha256)
            echo $SUM | sed 's:test-reporter-latest-linux-amd64:./tmp/cc-test-reporter:' > ./tmp/cc-test-reporter.sha256
      - restore_cache:
          key: cc-testreporter-v0-{{ arch }}-{{ checksum "tmp/cc-test-reporter.sha256" }}
      - run:
          name: Maybe Download cc-test-reporter
          command: |
            #!/usr/bin/env bash

            if sha256sum -c ./tmp/cc-test-reporter.sha256; then
              echo "cc-test-reporter has had no updates since last run"
              exit 0
            fi

            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./tmp/cc-test-reporter
            chmod +x ./tmp/cc-test-reporter
            ./tmp/cc-test-reporter before-build
      - save_cache:
          key: cc-testreporter-v0-{{ arch }}-{{ checksum "tmp/cc-test-reporter.sha256" }}
          paths:
            - ./tmp/cc-test-reporter
      - persist_to_workspace:
          root: tmp
          paths:
            - cc-test-reporter

  codeclimate-upload:
    executor: ruby-other
    steps:
      - attach_workspace:
          at: tmp
      - run:
          name: Upload coverage results to Code Climate
          command: |
            #!/usr/bin/env bash

            PART_COUNT=$(find tmp/ -name codeclimate.*.json -type f | wc -l)
            echo "Found ($PART_COUNT) parts"
            ./tmp/cc-test-reporter sum-coverage tmp/codeclimate.*.json --parts $PART_COUNT --output tmp/codeclimate.total.json
            ./tmp/cc-test-reporter upload-coverage --input tmp/codeclimate.total.json

  rubocop:
    executor: ruby-other
    steps:
      - checkout
      - load-dependencies
      - run:
          name: "Rubocop"
          command: |
            bundle exec rubocop --parallel

  typecheck:
    executor: ruby-other
    steps:
      - checkout
      - load-dependencies
      - run:
          name: "Sorbet Typecheck"
          command: |
            bundle exec srb tc

workflows:
  build:
    jobs:
      - codeclimate-setup
      - install-dependencies:
          matrix:
            parameters:
              version:
                - "3.0"
                - "3.1"
      - typecheck:
          requires:
            - install-dependencies-3.1
      - specs:
          matrix:
            parameters:
              version:
                - "3.0"
                - "3.1"
              appraisal:
                - standalone
                - rbnacl
          requires:
            - codeclimate-setup
            - install-dependencies-<< matrix.version >>
      - rubocop:
          requires:
            - install-dependencies-3.1
      - codeclimate-upload:
          requires:
            - specs
