module Paseto
  module V4
    class Local < Paseto::Key
      def encrypt: (message: String, ?footer: String, ?implicit_assertion: String) -> Token

      private
      
      def initialize: (ikm: String) -> void
    end
  end
end
