module Paseto
  module Key
    class AsymmetricSecret
      attr_reader material: String
      attr_reader version: Paseto::Versions::BaseVersion

      def initialize: (ikm: String, version: Paseto::Versions::BaseVersion) -> void
      def valid_for?: (version: Paseto::Versions::BaseVersion, purpose: 'secret') -> (false | true)
    end
  end
end