module RbNaCl
  module Stream
    class XChaCha20Xor < RbNaCl::Stream::Base
      extend Sodium

      def self.stream_xchacha20_xor: (String c, String m, Integer mlen, String n, String key) -> bool

      private

      def do_encrypt: (String ciphertext, String nonce, String message) -> bool

      KEYBYTES: Integer

      NONCEBYTES: Integer

      MESSAGEBYTES_MAX: Integer
    end
  end
end
