# DO NOT EDIT MANUALLY
# This is an autogenerated file for unresolved constants.
# Please instead update this file by running `bin/tapioca todo`.

# typed: false

module RuboCop::AST::NodePattern::Macros; end
module RuboCop::Cop::AutoCorrector; end
class RuboCop::Cop::Base; end
module RuboCop::Cop::ConfigurableEnforcedStyle; end
module RuboCop::Cop::RangeHelp; end
